config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from movies import views as movie_views

app_name = "core"

# 메인페이지
urlpatterns = [
    path("", movie_views.home_page, name="home"),
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("test", views.test, name="test"),
    path("<int:pk>", views.movie_detail, name="detail"),
    path("csv_test", views.csv_test, name="csv_test"),
    #path("search/", views.search_view, name="search"),
    path('api/finder/', views.tag_search, name="tag_search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.sign_up_view, name="signup"),
]

templates/partials/footer.html
푸터입니당~

templates/partials/nav.html
<header>
    <a href="{% url "core:home" %}">LAKEFLIX</a>
    <ul>
        <li><a class="nav-link" href="{% url 'movies:tag_search' %}">태그검색</a></li>
        <li><a class="nav-link" href="{% url 'movies:tag_search' %}">NEW/TREND</a></li>
        <li><a href="{% url "users:logout" %}">로그아웃</a></li>
    </ul>

</header>