config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from movies import views as movie_views

app_name = "core"

# 메인페이지
urlpatterns = [
    path("", movie_views.home_page, name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.sign_up_view, name="signup"),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <title>{% block page_title %}{% endblock page_title %} | Lakeflix</title>
</head>

<body class="text-gray-800 mt-24 font-light">
    {% if user.is_authenticated %}
    {% include "partials/nav.html" %}
    {% else %}
        <form class="form-inline my-2 my-lg-0">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item disabled">
                    <a class="nav-link" href="/">홈</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:login' %}">로그인</a>
                </li>
            </ul>
        </form>
    {% endif %}
    {% block content %}
    {% endblock %}
    {% include "partials/footer.html" %}
</body>

</html>