config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from movies import views as movie_views

app_name = "core"

# 메인페이지
urlpatterns = [
    path("", movie_views.home_page, name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.sign_up_view, name="signup"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """ User Model """
    class Meta:
        db_table = "user"

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (
            (GENDER_MALE, "남자"),
            (GENDER_FEMALE, "여자"),
            (GENDER_OTHER, "기타"),
        )
    )

    avatar = models.ImageField(null=True, upload_to="avatars")
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=10, null=True)
    bio = models.TextField(default="", blank=True)

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    username = forms.CharField(max_length=10, required=True)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(
                    "password", forms.ValidationError("패스워드가 다릅니다"))
        except models.User.DoesNotExist:
            self.add_error("username", forms.ValidationError(
                "유저가 존재하지 않습니다."))

users/views.py
from . models import User
from . import forms
from django.contrib import auth
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import logout


def sign_up_view(request):
    if request.method == 'GET':
        return render(request, 'users/signup.html')
    elif request.method == 'POST':
        avatar = request.POST.get("avatar", None)
        username = request.POST.get("username", None)
        password = request.POST.get("password", None)
        password2 = request.POST.get("password2", None)
        firstname = request.POST.get("firstname", None)
        lastname = request.POST.get("lastname", None)
        email = request.POST.get("email", None)
        gender = request.POST.get("gender", None)
        bio = request.POST.get("bio", None)

        if password != password2:
            return redirect(reverse("users:signup"))

        else:
            exist_user = User.objects.filter(username=username)
            if exist_user:
                return redirect(reverse("users:signup"))

            else:
                User.objects.create_user(
                    avatar=avatar,
                    username=username,
                    password=password,
                    first_name=firstname,
                    last_name=lastname,
                    email=email,
                    bio=bio,
                    gender=gender,
                )
            return redirect(reverse("users:login"))


def login_view(request):
    form = forms.LoginForm()
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        username = request.POST.get("username", None)
        password = request.POST.get("password", None)
        get_user = auth.authenticate(
            request, username=username, password=password)
        if get_user is not None:
            auth.login(request, get_user)
            return redirect("/")
        else:
            return render(request, 'users/login.html', {"form": form})
            # return redirect(reverse("users:login"))
    elif request.method == 'GET':
        form = forms.LoginForm()
        return render(request, 'users/login.html', {"form": form})


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))

templates/users/login.html
{% extends "base.html" %}
{% block page_title %}
로그인 페이지 입니당
{% endblock page_title %}
{% block content %}
<!-- <div>
    <h2>로그인</h2>
    <form class="form-area" method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        <div>
            <label for="username">이름</label>
            <input type="text" id="username" name="username" />
        </div>
        <div>
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password" />
        </div>
        <hr />
        <div>
            <button type="submit">로그인</button>
            <a href="{% url 'users:signup' %}" class="btn btn-secondary">회원가입 페이지로</a>
        </div>
    </form>
</div> -->
<!-- 폼테스트중 -->

<div>
    <h2>로그인</h2>
    <form class="form-area" method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">로그인</button>
    </form>
</div>

{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% block title %}
회원가입
{% endblock %}
{% block content %}
<div class="container">
    <h2> 회원가입 </h2>

    <form action="{% url 'users:signup' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="avatar">프로필 사진</label>
            <input type="file" accept=".jpg, .png" id="avatar" name="avatar">
        </div>
        <div>
            <label for="username">아이디</label>
            <input type="text" id="username" name="username">
        </div>
        <div>
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password">
        </div>
        <div>
            <label for="password2">비밀번호 확인</label>
            <input type="password" id="password2" name="password2">
        </div>

        <div>
            <label for="firstname">성</label>
            <input type="text" id="firstname" name="firstname">
        </div>

        <div>
            <label for="lastname">이름</label>
            <input type="text" id="lastname" name="lastname">
        </div>

        <div>
            <label for="email">이메일</label>
            <input type="email" id="email" name="email">
        </div>

        <div>
            <label class="required" for="gender">성별</label>
            <select name='gender' id="gender" required>
                <option value selected>-- 성별 --</option>
                <option value='male'>남자</option>
                <option value='female'>여자</option>
                <option value='other'>기타</option>
            </select>
        </div>
        <div>
            <label for="bio">자기소개</label>
            <textarea name="bio" cols="40" rows="10" class="vLargeTextField" id="id_bio"></textarea>
        </div>
        <hr>
        <div>
            <button type="submit" class="btn btn-primary">회원가입</button>
            <a href="{% url 'users:login' %}" class="btn btn-secondary">로그인 페이지로</a>
        </div>
    </form>
</div>
{% endblock %}